.TH ex1.7
.SH NAME
Ex1 - Command Line
.SH SYNOPSIS
Familiarizing with command line basics
.SH DESCRIPTION

ex1.tar.gz
a file that holds all the lines with the phrase "andriod_dev" in the kernel source folder
Indicated to the command output to this folder

ex1.7
File containing this information

.SH OPTIONS
none
.SH FILES
ex1.tar.gz
ex1.7
ex1-screenshot1.png
ex1-screenshot2.png
ex1-screenshot3.png

.SH SEE ALSO
Nothing

.SH TESTING
the ls command and the nano text editor

.SH AUTHOR
Charles Richardson
